resources:
#  - ./project.yaml
  - ./pvc.yaml
  - ./sa.yaml
  - ./service.yaml
  - ./statefulset.yaml
  - ./scc.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: create-schema
  behavior: create
  files:
    - create_schema.sh
