apiVersion: v1
kind: Service
metadata:
  name: analytics-db2
  labels:
    app: analytics-db2
spec:
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  clusterIP: None
  selector:
    app: analytics-db2
  sessionAffinity: None